###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [1]:
import numpy as np
np.random.seed(10)
arr = np.random.randint(0, 101, size=(4, 3))
print("Original Array:\n", arr)

sorted_rows = np.sort(arr)
print("Sorted Row-wise:\n", sorted_rows)

sort_col2 = arr[arr[:, 1].argsort()]
print("Sorted by 2nd Column:\n", sort_col2)

row_max_sort = arr[np.max(arr, axis=1).argsort()]
print("Sorted by Row Maximum:\n", row_max_sort)

flat_sorted = np.sort(arr, axis=None).reshape(arr.shape)
print("Sorted by Elements:\n", flat_sorted)


Original Array:
 [[  9 100  15]
 [ 64  28  89]
 [ 93  29   8]
 [ 73   0  40]]
Sorted Row-wise:
 [[  9  15 100]
 [ 28  64  89]
 [  8  29  93]
 [  0  40  73]]
Sorted by 2nd Column:
 [[ 73   0  40]
 [ 64  28  89]
 [ 93  29   8]
 [  9 100  15]]
Sorted by Row Maximum:
 [[ 73   0  40]
 [ 64  28  89]
 [ 93  29   8]
 [  9 100  15]]
Sorted by Elements:
 [[  0   8   9]
 [ 15  28  29]
 [ 40  64  73]
 [ 89  93 100]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [2]:
import numpy as np

marks = np.array([[13,10,9,33],
                  [63,46,90,42],
                  [39,76,13,29],
                  [82,9,29,78],
                  [67,61,59,36]])

extra_subject = np.array([41,87,72,36,92]).reshape(5,1)

marks = np.hstack((marks, extra_subject))

rec1 = np.array([[77,83,98,95,89]])
rec2 = np.array([[92,71,52,61,53]])
marks = np.vstack((marks, rec1, rec2))

total = marks.sum(axis=1).reshape(-1,1)
marks = np.hstack((marks, total))

sorted_marks = marks[marks[:, -1].argsort()[::-1]]
print("Top 2 Students:\n", sorted_marks[:2])


Top 2 Students:
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [3]:
import numpy as np

arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

unique_rows = np.unique(arr, axis=0)
print("Row Wise Unique:\n", unique_rows)

unique_cols = np.unique(arr.T, axis=0).T
print("Column Wise Unique:\n", unique_cols)


Row Wise Unique:
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
Column Wise Unique:
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [4]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

flipped = np.flip(arr)
print("Flipped Array:\n", flipped)

Flipped Array:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [5]:
import numpy as np

arr = np.array([[1,2,3,4,5],
                [10,-3,30,4,5],
                [3,2,5,-4,5],
                [9,7,3,6,5]])

X = 6
rows = np.where(np.any(arr > X, axis=1))[0]
print("Row indices:", rows)


Row indices: [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [6]:
import numpy as np

arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

flat_array = np.concatenate((arr1, arr2, arr3))
print("1D Array:", flat_array)

1D Array: [0 1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [7]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape(1,200)

min_val = arr.min()
max_val = arr.max()

filtered = arr[(arr != min_val) & (arr != max_val)]
print("Array after removing min & max:\n", filtered)


Array after removing min & max:
 [448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
 181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
 353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
 921 490 527 972 278 307 840 958 246 449 251 957 627 920 824 356 825 173
 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211 771
 270 308 231 952 514 699 702 433 900 373 318 265 503 320 230 324 922 967
 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930 325 729
 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528 395 525
 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859 618 226
 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748 291 194
 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207 883 588]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [8]:
import numpy as np

arr = np.random.randint(100, 701, 20)

clipped = np.clip(arr, 100, 200)
sorted_arr = np.sort(clipped)
cum_sum = np.cumsum(sorted_arr)

print("Final Cumulative Sum:\n", cum_sum)


Final Cumulative Sum:
 [ 200  400  600  800 1000 1200 1400 1600 1800 2000 2200 2400 2600 2800
 3000 3200 3400 3600 3800 4000]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [9]:
import numpy as np

arr = np.random.rand(20)
rounded = np.round(arr, 3)

p0 = np.percentile(rounded, 0)
p100 = np.percentile(rounded, 100)
p50 = np.percentile(rounded, 50)
p51 = np.percentile(rounded, 51)

print("0th Percentile:", p0)
print("100th Percentile:", p100)
print("Difference (51st - 50th):", p51 - p50)


0th Percentile: 0.041
100th Percentile: 0.974
Difference (51st - 50th): 0.017859999999999987
